drop table PEL_CAT_PEL;
drop table AUT_LIB;
drop table CANT_DISC_MUS;
drop table PEL_DIR;
drop table PEL_ACT;
drop table PEL_LEN;
drop table PEL_SUB;
drop table CATEGORIA_PEL;
drop table ACTOR;
drop table DIRECTOR;
drop table LENGUAJE;
drop table SUBTITULO;
drop table HISTORIAL;
drop table COMENTARIO
drop table USUARIO;
drop table PERSONA;
drop table ROL;
drop table ACCION;
drop table CARAC_VER;
drop table CARAC_SO;
drop table GEN_LIB_LIB;
drop table GEN_MU_DISC_MU;
drop table CALIFICACION;
drop table CARACTERISTICA ;
drop table VIDEO ;
drop table IMAGEN ;